version: "3"

services:
  sonarqube:
    image: sonarqube:9.2.4-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet2
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube9_conf:/opt/sonarqube/conf
      - sonarqube9_data:/opt/sonarqube/data
      - sonarqube9_extensions:/opt/sonarqube/extensions
      - sonarqube9_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:13.5
    networks:
      - sonarnet2
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql2:/var/lib/postgresql
      - postgresql2_data:/var/lib/postgresql/data

networks:
  sonarnet2:

volumes:
  sonarqube9_conf:
  sonarqube9_data:
  sonarqube9_extensions:
  sonarqube9_bundled-plugins:
  postgresql2:
  postgresql2_data:
